// Writes THIRD-PARTY-NOTICES.md: every piece of someone else's work that ships in the .vsix or the
// release's .rbxm, with its licence text. `--check` fails instead when the file is out of date, or when
// the esbuild bundles pull in an npm package not listed below (run by the unit tests).
import { readFileSync, writeFileSync } from "node:fs";
import { build } from "esbuild";

const OUT = "THIRD-PARTY-NOTICES.md";

// Bundled into dist/*.js by esbuild. The version and licence are read from node_modules.
const NPM = [
	{ name: "smol-toml", url: "https://github.com/squirrelchat/smol-toml", licenseFile: "LICENSE", in: "dist/service.js, dist/uninstall.js" },
	{ name: "jsonc-parser", url: "https://github.com/microsoft/node-jsonc-parser", licenseFile: "LICENSE.md", in: "dist/extension.js" },
	{ name: "@msgpack/msgpack", url: "https://github.com/msgpack/msgpack-javascript", licenseFile: "LICENSE", in: "dist/service.js" },
];

// Built into dist/RojoHub.rbxm from plugin/upstream/ (Rojo's plugin folder and its submodules, unedited) with
// Rojo-Hub's patches; versions come from plugin/upstream.json, which tools/plugin.mjs writes.
const UPSTREAM = JSON.parse(readFileSync("plugin/upstream.json", "utf8"));
const ROJO_VERSION = UPSTREAM.tag.replace(/^v/, "");
const ROJO = `https://github.com/rojo-rbx/rojo/tree/${UPSTREAM.tag}/plugin`;
const at = (name) => UPSTREAM.packages[name].slice(0, 7);
const PLUGIN = [
	{ name: "Rojo Studio plugin", version: ROJO_VERSION, license: "MPL-2.0", url: ROJO, licenseFile: "plugin/upstream/LICENSE.txt", in: "dist/RojoHub.rbxm (plugin/upstream/, with plugin/patches/)",
		note: "Modified by Rojo-Hub. plugin/upstream/ is Rojo's source unedited; the changes are the patches in [plugin/patches/](plugin/patches/), listed in [plugin/UPSTREAM.md](plugin/UPSTREAM.md). Rojo-Hub's own files (plugin/RojoHub/) are MIT." },
	{ name: "rbx_dom_lua (rbx-dom)", version: `as in Rojo ${ROJO_VERSION}`, license: "MIT", url: "https://github.com/rojo-rbx/rbx-dom", licenseFile: "plugin/rbx_dom_lua.LICENSE.txt", in: "dist/RojoHub.rbxm (plugin/upstream/rbx_dom_lua/)" },
	{ name: "Roact", version: at("Roact"), license: "Apache-2.0", url: "https://github.com/roblox/roact", licenseFile: "plugin/upstream/Packages/Roact/LICENSE.txt", in: "dist/RojoHub.rbxm (plugin/upstream/Packages/Roact/)", note: "Unmodified." },
	{ name: "Flipper", version: at("Flipper"), license: "MIT", url: "https://github.com/reselim/flipper", licenseFile: "plugin/upstream/Packages/Flipper/LICENSE", in: "dist/RojoHub.rbxm (plugin/upstream/Packages/Flipper/)" },
	{ name: "roblox-lua-promise", version: at("Promise"), license: "MIT", url: "https://github.com/evaera/roblox-lua-promise", licenseFile: "plugin/upstream/Packages/Promise/LICENSE", in: "dist/RojoHub.rbxm (plugin/upstream/Packages/Promise/)" },
	{ name: "t", version: at("t"), license: "MIT", url: "https://github.com/osyrisrblx/t", licenseFile: "plugin/upstream/Packages/t/LICENSE", in: "dist/RojoHub.rbxm (plugin/upstream/Packages/t/)" },
	{ name: "Highlighter", version: at("Highlighter"), license: "MIT", url: "https://github.com/boatbomber/highlighter", licenseFile: "plugin/upstream/Packages/Highlighter/LICENSE", in: "dist/RojoHub.rbxm (plugin/upstream/Packages/Highlighter/)" },
	{ name: "msgpack-luau", version: at("msgpack-luau"), license: "MIT", url: "https://github.com/cipharius/msgpack-luau", licenseFile: "plugin/upstream/Packages/msgpack-luau/LICENSE", in: "dist/RojoHub.rbxm (plugin/upstream/Packages/msgpack-luau/)" },
];

// Copied as files by build.mjs.
const CODICONS = [
	{ name: "@vscode/codicons (font)", license: "CC-BY-4.0", url: "https://github.com/microsoft/vscode-codicons", licenseFile: "node_modules/@vscode/codicons/LICENSE", in: "dist/codicons/codicon.ttf", note: "Unmodified." },
	{ name: "@vscode/codicons (stylesheet)", license: "MIT", url: "https://github.com/microsoft/vscode-codicons", licenseFile: "node_modules/@vscode/codicons/LICENSE-CODE", in: "dist/codicons/codicon.css", note: "Unmodified." },
];

const read = (file) => readFileSync(file, "utf8").replace(/^﻿/, "").replace(/\r\n/g, "\n").trimEnd();
const pkg = (name) => JSON.parse(readFileSync(`node_modules/${name}/package.json`, "utf8"));

function components() {
	const npm = NPM.map((c) => ({ ...c, version: pkg(c.name).version, license: pkg(c.name).license, licenseFile: `node_modules/${c.name}/${c.licenseFile}` }));
	const codiconsVersion = pkg("@vscode/codicons").version;
	return [...PLUGIN, ...npm, ...CODICONS.map((c) => ({ ...c, version: codiconsVersion }))];
}

function render() {
	const list = components();
	const lines = [
		"# Third-party notices",
		"",
		"Rojo-Hub is MIT ([LICENSE](LICENSE)). The extension package and the Studio plugin (`RojoHub.rbxm`) also",
		"contain the following work of others, each under its own licence, reproduced below. Generated by",
		"`node tools/notices.mjs`; do not edit by hand.",
		"",
		"Rojo-Hub is not affiliated with or endorsed by Roblox, the Rojo project, or any author below.",
		"",
		"| Component | Version | Licence | Source | Ships in |",
		"| --- | --- | --- | --- | --- |",
		...list.map((c) => `| ${c.name} | ${c.version} | ${c.license} | ${c.url} | ${c.in} |`),
		"",
	];
	for (const c of list) {
		lines.push(`## ${c.name} ${c.version}`, "", `${c.license}, from ${c.url}.${c.note ? ` ${c.note}` : ""}`, "", "```text", read(c.licenseFile), "```", "");
	}
	return lines.join("\n");
}

// npm packages esbuild actually puts in the bundles (same entry points and options as build.mjs).
async function bundledPackages() {
	const entries = [["src/extension/extension.ts", "node"], ["src/service/main.ts", "node"], ["src/extension/uninstall.ts", "node"], ["src/webview/main.ts", "browser"]];
	const found = new Set();
	for (const [entry, platform] of entries) {
		const { metafile } = await build({ entryPoints: [entry], platform, bundle: true, write: false, metafile: true, logLevel: "silent", mainFields: ["module", "main"], external: ["vscode"], outfile: "out.js" });
		for (const input of Object.keys(metafile.inputs)) {
			const match = input.match(/node_modules\/((?:@[^/]+\/)?[^/]+)/);
			if (match) found.add(match[1]);
		}
	}
	return [...found];
}

if (process.argv.includes("--check")) {
	const problems = [];
	const listed = new Set(NPM.map((c) => c.name));
	for (const name of await bundledPackages()) if (!listed.has(name)) problems.push(`${name} is bundled but not listed in tools/notices.mjs`);
	if (read(OUT) !== render().trimEnd()) problems.push(`${OUT} is out of date: run node tools/notices.mjs`);
	if (problems.length) {
		console.error(problems.join("\n"));
		process.exit(1);
	}
} else {
	writeFileSync(OUT, render());
	console.log(`Wrote ${OUT}`);
}
